version: '2'
services:
  db:
    image: postgres:9.6
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=1
    depends_on:
      - db
